FROM node:20-alpine
WORKDIR /app
COPY frontend/package*.json /app/
RUN npm ci
COPY frontend /app
ARG NEXT_PUBLIC_API_BASE=http://localhost:8000/api
ENV NEXT_PUBLIC_API_BASE=$NEXT_PUBLIC_API_BASE
RUN npm run build
CMD ["npm","start"]
